import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Sparkles, ArrowLeft, Send } from "lucide-react";
import { createTicket } from "../api/tickets";
import { useToast } from "../context/ToastContext";
import { apiError } from "../api/client";
import Card from "../components/Card";
import Button from "../components/Button";
import { Input, TextArea } from "../components/Input";

export default function TicketCreate() {
  const toast = useToast();
  const navigate = useNavigate();

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [submitting, setSubmitting] = useState(false);

  async function onSubmit(e) {
    e.preventDefault();
    if (submitting) return;
    setSubmitting(true);
    try {
      const { id } = await createTicket({
        title: title.trim(),
        description: description.trim(),
      });
      toast.success("Ticket created — AI is classifying it now");
      navigate(`/tickets/${id}`);
    } catch (err) {
      toast.error(apiError(err, "Failed to create ticket"));
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="mx-auto max-w-3xl">
      <Link
        to="/tickets"
        className="mb-4 inline-flex items-center gap-1.5 text-sm text-slate-400 hover:text-slate-200"
      >
        <ArrowLeft className="h-4 w-4" /> Back to tickets
      </Link>

      <h1 className="text-2xl font-bold text-slate-100">File a new ticket</h1>
      <p className="mt-1 text-sm text-slate-400">
        Describe your issue. Our AI will set the priority, add tags, and draft a first response.
      </p>

      <Card padding="lg" className="mt-6">
        <form onSubmit={onSubmit} className="flex flex-col gap-5">
          <Input
            label="Title"
            name="title"
            placeholder="e.g. Cannot log in — getting 500 errors"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            required
            maxLength={140}
            hint={`${title.length}/140`}
          />

          <TextArea
            label="Description"
            name="description"
            placeholder="What's happening? When did it start? Any error messages or steps to reproduce?"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            rows={7}
            required
            minLength={10}
          />

          <div className="rounded-lg border border-indigo-500/20 bg-indigo-500/5 p-3">
            <div className="flex items-start gap-2">
              <Sparkles className="mt-0.5 h-4 w-4 text-indigo-300" />
              <div className="text-xs text-slate-400">
                <p className="font-medium text-slate-200">AI auto-classification</p>
                <p className="mt-0.5">
                  Priority, tags, and a suggested reply will be generated by Google Gemini and
                  attached to your ticket. You can ask an agent to re-run analysis later.
                </p>
              </div>
            </div>
          </div>

          <div className="flex items-center justify-end gap-3">
            <Link to="/tickets">
              <Button variant="ghost" type="button">
                Cancel
              </Button>
            </Link>
            <Button type="submit" loading={submitting}>
              <Send className="h-4 w-4" /> Submit ticket
            </Button>
          </div>
        </form>
      </Card>
    </div>
  );
}
