import { useEffect, useState, useCallback } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import {
  ArrowLeft,
  RefreshCw,
  Trash2,
  Sparkles,
  Quote,
  UserPlus,
  Calendar,
  Clock,
  User,
  Hash,
} from "lucide-react";
import { getTicket, reanalyzeTicket, deleteTicket, assignTicket } from "../api/tickets";
import { listAgents } from "../api/users";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";
import { apiError } from "../api/client";
import Card from "../components/Card";
import Button from "../components/Button";
import { PriorityBadge, StatusBadge, Tag } from "../components/Badge";
import { PageSpinner } from "../components/Spinner";
import { formatDateTime, formatRelative } from "../lib/format";

export default function TicketDetail() {
  const { id } = useParams();
  const { user } = useAuth();
  const toast = useToast();
  const navigate = useNavigate();

  const [ticket, setTicket] = useState(null);
  const [loading, setLoading] = useState(true);
  const [reanalyzing, setReanalyzing] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [confirmingDelete, setConfirmingDelete] = useState(false);

  const fetchTicket = useCallback(async () => {
    setLoading(true);
    try {
      const t = await getTicket(id);
      setTicket(t);
    } catch (err) {
      toast.error(apiError(err, "Failed to load ticket"));
      navigate("/tickets");
    } finally {
      setLoading(false);
    }
  }, [id, navigate, toast]);

  useEffect(() => {
    fetchTicket();
  }, [fetchTicket]);

  async function onReanalyze() {
    setReanalyzing(true);
    try {
      const { ai } = await reanalyzeTicket(id);
      setTicket((t) => (t ? { ...t, ...ai, updatedAt: new Date().toISOString() } : t));
      toast.success("AI re-analyzed this ticket");
    } catch (err) {
      toast.error(apiError(err, "Re-analysis failed"));
    } finally {
      setReanalyzing(false);
    }
  }

  async function onDelete() {
    setDeleting(true);
    try {
      await deleteTicket(id);
      toast.success("Ticket deleted");
      navigate("/tickets");
    } catch (err) {
      toast.error(apiError(err, "Delete failed"));
      setDeleting(false);
    }
  }

  if (loading) return <PageSpinner label="Loading ticket…" />;
  if (!ticket) return null;

  const isOwner = ticket.user_id === user.id;
  const isAdmin = user.role === "admin";
  const canDelete = isOwner || isAdmin;

  return (
    <div className="flex flex-col gap-6">
      <Link
        to="/tickets"
        className="inline-flex w-fit items-center gap-1.5 text-sm text-slate-400 hover:text-slate-200"
      >
        <ArrowLeft className="h-4 w-4" /> Back to tickets
      </Link>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="flex flex-col gap-6 lg:col-span-2">
          <Card padding="lg">
            <div className="flex flex-wrap items-center gap-2">
              <PriorityBadge value={ticket.priority} />
              <StatusBadge value={ticket.status} />
            </div>
            <h1 className="mt-3 text-2xl font-bold text-slate-100">{ticket.title}</h1>
            <div className="mt-4 whitespace-pre-wrap text-sm leading-relaxed text-slate-300">
              {ticket.description}
            </div>
          </Card>

          <Card padding="lg" className="relative overflow-hidden">
            <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-indigo-500/40 to-transparent" />
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-2">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-500 to-violet-500 shadow-lg shadow-indigo-500/30">
                  <Sparkles className="h-4 w-4 text-white" />
                </div>
                <div>
                  <h2 className="text-base font-semibold text-slate-100">AI Analysis</h2>
                  <p className="text-xs text-slate-500">Generated by Gemini</p>
                </div>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={onReanalyze}
                loading={reanalyzing}
              >
                <RefreshCw className="h-3.5 w-3.5" /> Reanalyze
              </Button>
            </div>

            <div className="mt-5">
              <h3 className="text-xs font-medium uppercase tracking-wider text-slate-500">Tags</h3>
              <div className="mt-2 flex flex-wrap gap-1.5">
                {(ticket.tags || []).length > 0 ? (
                  ticket.tags.map((t) => <Tag key={t}>{t}</Tag>)
                ) : (
                  <span className="text-sm text-slate-500">No tags yet.</span>
                )}
              </div>
            </div>

            <div className="mt-5">
              <h3 className="text-xs font-medium uppercase tracking-wider text-slate-500">
                Suggested reply
              </h3>
              <div className="mt-2 rounded-lg border border-slate-800 bg-slate-950/40 p-4">
                {ticket.suggested_reply ? (
                  <div className="flex gap-3">
                    <Quote className="h-4 w-4 shrink-0 text-indigo-400" />
                    <p className="whitespace-pre-wrap text-sm leading-relaxed text-slate-300">
                      {ticket.suggested_reply}
                    </p>
                  </div>
                ) : (
                  <p className="text-sm text-slate-500">
                    No suggestion available — the AI returned defaults. Click Reanalyze to retry.
                  </p>
                )}
              </div>
            </div>
          </Card>
        </div>

        <div className="flex flex-col gap-4">
          <Card padding="md">
            <h3 className="text-xs font-medium uppercase tracking-wider text-slate-500">Details</h3>
            <dl className="mt-3 space-y-3 text-sm">
              <DetailRow icon={Hash} label="ID" value={ticket._id} mono />
              <DetailRow
                icon={Calendar}
                label="Created"
                value={formatDateTime(ticket.createdAt)}
                hint={formatRelative(ticket.createdAt)}
              />
              <DetailRow
                icon={Clock}
                label="Updated"
                value={formatDateTime(ticket.updatedAt)}
                hint={formatRelative(ticket.updatedAt)}
              />
              <DetailRow
                icon={User}
                label="Owner"
                value={isOwner ? "You" : ticket.user_id}
                mono={!isOwner}
              />
              <DetailRow
                icon={UserPlus}
                label="Assigned agent"
                value={ticket.assigned_agent_id || "Unassigned"}
                mono={!!ticket.assigned_agent_id}
              />
            </dl>
          </Card>

          {isAdmin && <AssignAgentCard ticket={ticket} onAssigned={fetchTicket} />}

          {canDelete && (
            <Card padding="md">
              <h3 className="text-xs font-medium uppercase tracking-wider text-slate-500">
                Danger zone
              </h3>
              <p className="mt-2 text-sm text-slate-400">
                Deleting a ticket removes it permanently. This can't be undone.
              </p>
              {confirmingDelete ? (
                <div className="mt-3 flex items-center gap-2">
                  <Button
                    variant="danger"
                    size="sm"
                    onClick={onDelete}
                    loading={deleting}
                  >
                    <Trash2 className="h-3.5 w-3.5" /> Yes, delete
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setConfirmingDelete(false)}
                  >
                    Cancel
                  </Button>
                </div>
              ) : (
                <Button
                  variant="outline"
                  size="sm"
                  className="mt-3 text-red-300 hover:!bg-red-500/10"
                  onClick={() => setConfirmingDelete(true)}
                >
                  <Trash2 className="h-3.5 w-3.5" /> Delete ticket
                </Button>
              )}
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}

function DetailRow({ icon: Icon, label, value, hint, mono }) {
  return (
    <div className="flex items-start gap-2.5">
      <Icon className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-500" />
      <div className="min-w-0 flex-1">
        <dt className="text-xs text-slate-500">{label}</dt>
        <dd
          className={
            "truncate text-sm text-slate-200 " + (mono ? "font-mono text-xs" : "")
          }
          title={value}
        >
          {value}
        </dd>
        {hint && <p className="text-xs text-slate-500">{hint}</p>}
      </div>
    </div>
  );
}

function AssignAgentCard({ ticket, onAssigned }) {
  const toast = useToast();
  const [agents, setAgents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(ticket.assigned_agent_id || "");
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    let cancelled = false;
    listAgents()
      .then((res) => {
        if (!cancelled) setAgents(res);
      })
      .catch((err) => toast.error(apiError(err, "Failed to load agents")))
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
  }, [toast]);

  async function onAssign() {
    if (!selected) return;
    setSubmitting(true);
    try {
      await assignTicket(ticket._id, selected);
      toast.success("Agent assigned");
      onAssigned();
    } catch (err) {
      toast.error(apiError(err, "Assignment failed"));
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Card padding="md">
      <h3 className="text-xs font-medium uppercase tracking-wider text-slate-500">Assign agent</h3>
      <div className="mt-3 flex flex-col gap-2">
        <select
          value={selected}
          onChange={(e) => setSelected(e.target.value)}
          disabled={loading}
          className="w-full rounded-lg border border-slate-700 bg-slate-900/60 px-3 py-2 text-sm text-slate-100 focus:border-indigo-500/60 focus:outline-none focus:ring-2 focus:ring-indigo-500/30"
        >
          <option value="">{loading ? "Loading agents…" : "Select an agent…"}</option>
          {agents.map((a) => (
            <option key={a._id} value={a._id}>
              {a.name} — {a.email}
            </option>
          ))}
        </select>
        <Button
          size="sm"
          onClick={onAssign}
          loading={submitting}
          disabled={!selected || selected === ticket.assigned_agent_id}
        >
          <UserPlus className="h-3.5 w-3.5" /> Assign
        </Button>
      </div>
    </Card>
  );
}
